production:
  <<: *default
  database: <%= ENV['bookers2'] %>
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV['root.c0h8rsgcqdhs.ap-northeast-1.rds.amazonaws.com'] %>
  username: <%= ENV['root'] %>
  password: <%= ENV['11424321'] %>